#! /bin/sh

### AUTOSTART ###

sxhkd &

xrandr --auto

ibus-daemon &

xsetroot -cursor_name left_ptr

pidof bspswallow || bspswallow &

~/.config/bspwm/config_monitor.sh
bspc desktop -f 1

# polybar
#$HOME/.config/polybar/launch-bspwm.sh &

#bspc config border_radius                 8
bspc config border_width                  2
bspc config window_gap                    4
bspc config top_padding                   22
bspc config bottom_padding                0
bspc config left_padding                  0
bspc config right_padding                 0
bspc config single_monocle                true
bspc config click_to_focus                true
bspc config split_ratio                   0.50
bspc config borderless_monocle            true
bspc config gapless_monocle               true
#bspc config focus_by_distance             true
bspc config focus_follows_pointer         true
#bspc config history_aware_focus           true
bspc config remove_disabled_monitors      true
bspc config merge_overlapping_monitors    true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
#bspc config automatic_scheme longest_side
#bspc config initial_polarity second_child

#### BSPWM coloring ####
bspc config normal_border_color		      "#4c566a"
bspc config active_border_color		      "#1e1e1e" 
bspc config focused_border_color	      "#c98e00"
bspc config presel_feedback_color	      "#5e81ac"
bspc config urgent_border_color 	      "#dd2727"


### RULES ###
bspc rule -a Gimp desktop='^4' state=floating follow=on
bspc rule -a Zathura state=tiled follow=on
bspc rule -a Google-chrome desktop='1'
bspc rule -a google-chrome desktop='1'
bspc rule -a Firefox desktop='4'
bspc rule -a VNote-2.9-x86_64.AppImage desktop='7'

# speed up the keyboard
xset r rate 200 60

# swap ESC and Capslock
#xmodmap ~/.config/bspwm/swapkeys -display :0
setxkbmap -option caps:swapescape

# natural scrolling
synclient NaturalScrolling=1 VertScrollDelta=-100 MaxSpeed=1.2 MinSpeed=0.8
xinput set-prop 15 279 1
xinput set-prop 15 288 -0.7

# wallpaper
feh --randomize --bg-fill /home/dupham/Pictures/backgrounds

# Fix PyCharm blank screen
wmname LG3D

# autostart apps
if [ $# -eq 0 ] 
then
    google-chrome&
    firefox&
    /home/dupham/apps/VNote-2.9-x86_64.AppImage&
fi
