#! /bin/sh

### AUTOSTART ###

sxhkd &

#xrandr -s 0 && xrandr --auto

xsetroot -cursor_name left_ptr

# pidof bspswallow || bspswallow &

if [ $1 -eq 0 ]; then
    echo "configuring new workspaces"
    ~/.config/bspwm/config_monitor.sh
else
    echo "move workspaces"
    ~/.config/bspwm/move_desktops.sh
fi
bspc desktop -f 1

# polybar
#$HOME/.config/polybar/launch-bspwm.sh &

#bspc config border_radius                 8
bspc config border_width                  2
bspc config window_gap                    4
bspc config top_padding                   24
bspc config bottom_padding                0
bspc config left_padding                  0
bspc config right_padding                 0
bspc config single_monocle                true
bspc config click_to_focus                true
bspc config split_ratio                   0.52
bspc config borderless_monocle            true
bspc config gapless_monocle               true
#bspc config focus_by_distance             true
bspc config focus_follows_pointer         true
bspc config pointer_follows_focus         true
#bspc config history_aware_focus           true
bspc config remove_disabled_monitors      true
bspc config merge_overlapping_monitors    true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
#bspc config automatic_scheme longest_side
#bspc config initial_polarity second_child

#### BSPWM coloring ####
bspc config normal_border_color		      "#4c566a"
bspc config active_border_color		      "#1e1e1e" 
bspc config focused_border_color	      "#c98e00"
bspc config presel_feedback_color	      "#5e81ac"
bspc config urgent_border_color 	      "#dd2727"


### RULES ###
bspc rule -a Gimp desktop='^4' state=floating follow=on
bspc rule -a Zathura state=tiled follow=on
bspc rule -a '*:*:Zoom Meeting' desktop='^1' state=tiled follow=on

# speed up the keyboard
xset r rate 200 60

# swap ESC and Capslock
#xmodmap ~/.config/bspwm/swapkeys -display :0
setxkbmap -option caps:swapescape

# mouse config
synclient VertScrollDelta=-100 MaxSpeed=1.2 MinSpeed=0.8
xinput set-prop 12 322 3.5

# wallpaper
#feh --randomize --bg-fill /home/duypham/Pictures/wallpapers

# Fix PyCharm blank screen
wmname LG3D

ibus-daemon &

xrdb ~/.Xdefaults &

xss-lock -- betterlockscreen -l &
