#! /bin/sh

sxhkd &

xrandr --auto

# monitors positions
xrandr --output DVI-I-1-1 --right-of DVI-I-2-2
xrandr --output eDP-1 --below DVI-I-1-1
xrandr --output DVI-I-1-1 --primary

source ~/.config/bspwm/detect_monitor.sh
~/.config/bspwm/config_monitor.py
bspc desktop -f 1

# polybar
$HOME/.config/polybar/launch-bspwm.sh &

#bspc config border_radius                8
bspc config border_width                  3
bspc config window_gap                    5
bspc config top_padding                   16
bspc config bottom_padding                0
bspc config left_padding                  0
bspc config right_padding                 0
bspc config single_monocle                false
bspc config click_to_focus                true
bspc config split_ratio                   0.50
bspc config borderless_monocle            true
bspc config gapless_monocle               true
#bspc config focus_by_distance             true
bspc config focus_follows_pointer         true
#bspc config history_aware_focus           true
bspc config remove_disabled_monitors      true
bspc config merge_overlapping_monitors    true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
#bspc config automatic_scheme longest_side
bspc config initial_polarity second_child

#### BSPWM coloring ####
bspc config normal_border_color		      "#4c566a"
bspc config active_border_color		      "#1e1e1e" 
bspc config focused_border_color	      "#4c7899"
bspc config presel_feedback_color	      "#5e81ac"
bspc config urgent_border_color 	      "#dd2727"


bspc rule -a Gimp desktop='^4' state=floating follow=on
bspc rule -a Chromium desktop='1'
#bspc rule -a mplayer2 state=floating
bspc rule -a KeePass2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off

# speed up the keyboard
xset r rate 200 60

# swap ESC and Capslock
setxkbmap -option caps:swapescape

# natural scrolling
synclient NaturalScrolling=1 VertScrollDelta=-100 MaxSpeed=1.2 MinSpeed=0.8
xinput set-prop 13 314 1
xinput set-prop 13 323 -0.5

# wallpaper
feh --bg-scale --randomize /usr/share/backgrounds

# Fix PyCharm blank screen
wmname LG3D
