#! /bin/sh

if [ $1 -eq 1 ]; then
    echo "move workspaces"
    ~/.config/bspwm/move_desktops.sh &
    bspc desktop -f 1 &
else
    echo "configuring new workspaces"
    ~/.config/bspwm/config_monitor.sh &&
    bspc desktop -f 1 &
    sxhkd &
    #redshift &
    lxappearance & alacritty &
    nm-applet &
    blueman-applet &
    picom --fade-in-step=1 --fade-out-step=1 --fade-delta=0 &
    pgrep bspswallow || bspswallow &
fi

#bspc config border_radius                8
bspc config border_width                  2
bspc config window_gap                    8
bspc config top_padding                   30
bspc config bottom_padding                0
bspc config left_padding                  0
bspc config right_padding                 0
bspc config single_monocle                true
bspc config click_to_focus                true
bspc config split_ratio                   0.5
bspc config borderless_monocle            true
bspc config gapless_monocle               false
#bspc config focus_by_distance             true
bspc config focus_follows_pointer         true
bspc config pointer_follows_focus         true
#bspc config history_aware_focus           true
bspc config remove_disabled_monitors      true
bspc config merge_overlapping_monitors    true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
#bspc config automatic_scheme longest_side
#bspc config initial_polarity second_child

#### BSPWM coloring ####
bspc config normal_border_color		      "#4c566a"
bspc config active_border_color		      "#1e1e1e" 
bspc config focused_border_color	      "#cea600"
bspc config presel_feedback_color	      "#5e81ac"
bspc config urgent_border_color 	      "#dd2727"


bspc rule -a Gimp state=floating follow=on
bspc rule -a Zathura state=tiled follow=on
bspc rule -a pavucontrol state=floating follow=on

# swap ESC and Capslock
~/.config/bspwm/input-settings.sh
~/.config/bspwm/monitor-hotplug.sh

# wallpaper
feh --bg-fill --randomize /home/duy/Pictures/wallpapers/

# Fix PyCharm blank screen
wmname LG3D

#/home/duy/work/Programs/bspswallow/bspswallow &
~/.config/bspwm/auto_dpi.sh &
#xrdb ~/.Xdefaults &

$HOME/.config/polybar/launch.sh &

